---
# tasks file for ansible-role-logitech
- name: Update cache for Debian-based distros
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  changed_when: false
  become: true

- name: Include vars for the required distribution
  include_vars: "{{ ansible_facts['os_family']}}.yml"

- name: Install dependencies
  package:
    name: "{{ dependencies }}"
    state: present
  become: true

- name: Make sure the source directory exists
  file:
    path: "{{ src_dir }}"
    state: directory

- name: Make sure that the logiops source directory exists
  stat:
    path: "{{ src_dir }}/logiops"
  register: logiops_dir

- name: Copy the project from GitHub
  git:
    repo: https://github.com/PixlOne/logiops
    dest: "{{ src_dir }}/logiops"
    force: true
    update: "{{ upgrade | default(false) }}"
  register: new_version

- name: Make sure the build directory is present
  file:
    path: "{{ src_dir }}/logiops/build"
    state: directory

- name: Compile logiops
  command:
    cmd: "cmake .."
    chdir: "{{ src_dir }}/logiops/build"
  when: new_version.changed

- name: Install logiops
  shell:
    cmd: "sudo make install"
    chdir: "{{ src_dir }}/logiops/build"
    warn: false
  when: new_version.changed

- name: Copy the logid systemd service over from the global folder
  template:
    src: "../../../config_files/logid/systemd-service"
    dest: /etc/systemd/system/logid.service
  become: true
  register: global_config

- name: Copy the logid systemd service over (if global fails)
  template:
    src: files/logid/systemd-service
    dest: /etc/systemd/system/logid.service
  become: true
  when: global_config.failed

- name: Copy the logid.cfg over from the global folder
  template:
    src: "../../..//logid/logid.cfg"
    dest: /etc/logid.cfg
  become: true
  ignore_errors: true
  register: global_config

- name: Copy the logid.cfg over (if global fails)
  template:
    src: files/logid/logid.cfg
    dest: /etc/logid.cfg
  become: true
  when: global_config.failed

- name: Make sure that logid is started
  service:
    name: logid
    state: started
    enabled: true
  become: true

- name: Restart logid
  service:
    name: logid
    state: restarted
    enabled: true
  become: true
  when: new_version.changed
